apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: gitops
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
  datacenterRef:
    kind: DockerDatacenterConfig
    name: gitops
  externalEtcdConfiguration:
    count: 1
  gitOpsRef:
    kind: GitOpsConfig
    name: gitops
  kubernetesVersion: "1.22"
  managementCluster:
    name: gitops
  workerNodeGroupConfigurations:
  - count: 2
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  name: gitops
  namespace: default
spec: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: GitOpsConfig
metadata:
  name: gitops
  namespace: default
spec:
  flux:
    github:
      branch: main
      clusterConfigPath: clusters/gitops
      fluxSystemNamespace: flux-system
      owner: toj900
      personal: true
      repository: gitops

---
